lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - ro-crate-metadata.json
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Niklas Schandry
  description: Assemble genomes from long ONT or pacbio HiFi reads
  force: false
  is_nfcore: true
  name: genomeassembler
  org: nf-core
  outdir: .
  version: 1.0.0
linting:
  files_unchanged:
    - ".github/CONTRIBUTING.md"
    - "assets/sendmail_template.txt"
  files_exist:
    - "assets/multiqc_config.yml"
  multiqc_config: False
