nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: "@mahesh-panchal;@d4straub"
  description: Genome assembly and annotation pipeline for prokaryotes and eukaryotes
  force: false
  is_nfcore: true
  name: genomeassembler
  org: nf-core
  outdir: .
  version: 1.0dev
