name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/genomeassembler') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.04.2"
          - "latest-everything"
        ASSEMBLER:
          - "hifi_flye"
          - "hifi_hifiasm"
          - "ont_flye"
          - "hifiont_hifiasm"
          - "hifiont_flyehifiasm"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: "Run pipeline with test data ${{ matrix.ASSEMBLER }}"
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker,${{ matrix.ASSEMBLER }}  --outdir ./results_${{ matrix.ASSEMBLER }}
